


node {
    
     def path='product-catalog-service'
    
     stage('Checkout') {
         git url: 'https://github.com/nagabhushanamn/shop-micro-services.git',branch: 'master' 
     }
     
     stage('Compile & Test') {
     	dir(path){
     		sh 'mvn test'
     	}
     }
     
     stage('Package') {
     	dir(path){
     		sh 'mvn package'
     	}
     }
     
     
     stage('Docker Image') {
     	dir(path){
     	    def app = docker.build "localhost:5000/pc-service"
            app.push()
     	}
     }
     
     stage ('Run Docker-container') {
        sh 'docker stop $(docker ps -a -q)'
        docker.image("localhost:5000/pc-service").run('-p 8081:8080')
    }
     
     
    
}